name: DevSecOps End to End Pipeline

on:
    push:
        branches: [main]

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secrets-scan:
        uses: ./.github/workflows/code-quality.yml
        secrets: inherit
    
    dependency-scan:
        uses: ./.github/workflows/dependency-sacn.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml


