#This is workflow name 
name: Hello

#runs on a trigger, whenever change is pushed to branch [deployment]
on:
  push:
    branches: [main]

#These are jobs inside the workflow
jobs:

#These is the name of the job
    greet:
    #this is github runner,each job runs on runner
      runs-on: ubuntu-latest
    
      steps:
        - name: say hello to users
          run: echo "Hello Dosto"

        - name: say hello to username
          run: echo "Hello $USER"
    details:
        runs-on: ubuntu-latest
        steps:
            - name: show what is the version of python, docker, etc
              run: docker --version && python --version
