# This is the workflow name
name: Hello

# Runs on a trigger
on:
  push:
    branches: [main]
# These are the jobs inside the workflow
jobs:

# This is the name of the job
  greet:
# This is a github runner, each job runs on a runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"

      - name:
        run: echo "Hello $USER"
