name: System Info

on:
  workflow_dispatch: 

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - name: Show OS
        run: uname -a

      - name: Show Date
        run: date

      - name: Show Current User
        run: whoami
